<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="Eshwar" name="testNGFrameWorkBasics.TestCase4DependsOnMethods" tests="3" failures="1" timestamp="2021-05-25T16:57:52 IST" time="0.001" errors="0">
  <testcase name="firstTestCase" time="0.000" classname="testNGFrameWorkBasics.TestCase4DependsOnMethods">
    <skipped/>
  </testcase> <!-- firstTestCase -->
  <system-out/>
  <testcase name="doLogin" time="0.001" classname="testNGFrameWorkBasics.TestCase4DependsOnMethods">
    <failure type="java.lang.AssertionError" message="TEst Case fail due to conditions not met">
      <![CDATA[java.lang.AssertionError: TEst Case fail due to conditions not met
at org.testng.Assert.fail(Assert.java:99)
at testNGFrameWorkBasics.TestCase4DependsOnMethods.doLogin(TestCase4DependsOnMethods.java:12)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- doLogin -->
  <system-out/>
  <testcase name="doUserReg" time="0.000" classname="testNGFrameWorkBasics.TestCase4DependsOnMethods">
    <skipped/>
  </testcase> <!-- doUserReg -->
  <system-out/>
</testsuite> <!-- testNGFrameWorkBasics.TestCase4DependsOnMethods -->
